# COCO 2017 dataset http://cocodataset.org

data:
  dataset_name: coco

  train_set: /home/mindocr/mikecheung/data/PubLayNet/publaynet/train2017.txt  # 118287 images
  val_set: /home/mindocr/mikecheung/data/PubLayNet/publaynet/val2017.txt  # 5000 images
  test_set: /home/mindocr/mikecheung/data/PubLayNet/publaynet/val2017.txt  # 20288 of 40670 images, submit to https://competitions.codalab.org/competitions/20794

  nc: 5

  # class names
  names: [ 'title', 'text', 'figure', 'table', 'list' ]

  train_transforms: []
  test_transforms: []